name: GitHub Actions on PR merge/close
run-name: ${{ github.actor }} running this 🚀

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  merge_job:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged
  close_job:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was closed
